// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.AppConfig>;

export function GetSysInfo():Promise<main.SysPayload>;

export function GetSystemInfo():Promise<main.SystemPayload>;

export function RelaunchAsAdmin():Promise<void>;

export function StartInstallation(arg1:main.InstallConfig):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimize():Promise<void>;

export function WindowToggleMaximize():Promise<void>;
