// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSysInfo() {
  return window['go']['main']['App']['GetSysInfo']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function RelaunchAsAdmin() {
  return window['go']['main']['App']['RelaunchAsAdmin']();
}

export function StartInstallation(arg1) {
  return window['go']['main']['App']['StartInstallation'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimize() {
  return window['go']['main']['App']['WindowMinimize']();
}

export function WindowToggleMaximize() {
  return window['go']['main']['App']['WindowToggleMaximize']();
}
